-- テーブル削除
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

-- users テーブルを作成するクエリ
CREATE TABLE users
(
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT,
	password TEXT,
	email TEXT
);

--tasks テーブルを作成するクエリ
CREATE TABLE tasks
(
	task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER,
	category_id INTEGER,
	title TEXT,
	closing_date DATE,
	progress INTEGER,
	memo TEXT,
	
	time INTEGER,
	date DATE
);

-- categories テーブルを作成するクエリ
CREATE TABLE categories
(
	category_id INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
	category_name VARCHAR(20)
);